### ISSUE TITLE
Select Certain Zones

### ISSUE THREAD

**Issue by mattttt** [raintank/ns1-app#6]
Currently, the NS1 app will get all zones, but some NS1 customers have hundreds of thousands of zones and do not want to scrape & store all that data. 

We need to extend the application to accept specific zones or get creative on how to solve this.

**Comment by woodsaj** [comment]
@mattttt I think we need to develop this from the UI first.  Any thoughts on how to enable users to "select" the zones they want.

some options:
- We could use include/exclude regexp filters eg.  include: `.*\.io`, exclude: `raintank\.io`
- We can easily enough query the NS1 api from within the ns1-app config page to list all zones and allow users to select the specific zones they want.

**Comment by mattttt** [comment]
Spoke with the NS1 team (and subsequently @woodsaj) and decided that in v1:
- Customers will manually enter zones for the first version of the app.
- Each zone will register as its own Snap task.
- NS1 to decide the max # of zones initially.

**Comment by woodsaj** [comment]
This was completed in the v1 deployment
